files:
  - source: /src/translations/en/**/*.json
    translation: /src/translations/%two_letters_code%/**/%original_file_name%
  - source: /src/translations/en/**/*.mdx
    translation: /src/translations/%two_letters_code%/**/%original_file_name%
