---
- name: Install common required packages
  apt:
    pkg:
      - build-essential
      - nano
      - telnet
      - curl
      - ca-certificates
      - gnupg
      - git
      - zip
    update_cache: yes
    state: latest
