---
- name: Install Chromium — Debian
  apt:
    pkg:
      - chromium
    update_cache: yes
    state: latest
  when: ansible_distribution == 'Debian'

- name: Install Chromium — Ubuntu
  apt:
    pkg:
      - chromium-browser
    update_cache: yes
    state: latest
  when: ansible_distribution == 'Ubuntu'

  # See https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#recommended-enable-user-namespace-cloning
- name: Enable user namespace cloning to allow running Chromium in a sandbox
  command: sysctl -w kernel.unprivileged_userns_clone=1
  when: ansible_facts['architecture'] != 'aarch64'
