---
- name: Setup ota-contribution-tool infrastructure
  hosts: all
  become: yes

- import_playbook: playbooks/infra/common.yml
- import_playbook: playbooks/infra/git.yml
- import_playbook: playbooks/infra/node.yml
- import_playbook: playbooks/infra/chromium.yml
